name: Housekeeping
on:
  push:
jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - run: |-
          go mod tidy
          go mod download

      - name: Lint
        run: make lint

      - name: Build binary
        run: make build
      
      - name: Unit tests
        run: make test
      
      - name: Integration tests
        run: make integration-test


  
  lint-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Vacuum
        run: |
          curl -fsSL https://quobix.com/scripts/install_vacuum.sh | sh
          vacuum lint -dexq openapi.yaml
